- menu_name: "Site Services"

- name: "Contact"
  url: "/contact/"
  title: "IS-ENES3 contact"

- name: "Subscribe to our newsletter"
  url: "https://lists.enes.org/mailman/listinfo/is-enes3"
  title: "Subscribe to IS-ENES3 newsletter"

- name: "Privacy Policy"
  url: "/privacy/"
  title: "IS-ENES3 Privacy Policy"

- name: "Credits"
  url: "/credits/"
  title: "Site and photo credits"
