- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "IS-ENES3 contact"

- name: "Subscribe to our newsletter"
  url: "https://lists.enes.org/mailman/listinfo/is-enes3"
  title: "Subscribe to newsletter"

- name: "Privacy Policy"
  url: "/privacy/"
  title: "IS-ENES3 privacy policy"
